Models/tb_EMPLOYEE.cs
namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class tb_EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_EMPLOYEE()
        {
            tb_ACCOUNT = new HashSet<tb_ACCOUNT>();
            tb_ATTENDANCE = new HashSet<tb_ATTENDANCE>();
            tb_CONTRACT = new HashSet<tb_CONTRACT>();
            tb_EMPLOYEE_ALLOWANCE = new HashSet<tb_EMPLOYEE_ALLOWANCE>();
            tb_INSURANCE = new HashSet<tb_INSURANCE>();
            tb_OVERTIME = new HashSet<tb_OVERTIME>();
            tb_REWARD_DISCIPLINE = new HashSet<tb_REWARD_DISCIPLINE>();
            tb_SALARY_ADVANCE = new HashSet<tb_SALARY_ADVANCE>();
        }
        public tb_EMPLOYEE(int employeeID, string fullName, string gender, DateTime? dateOfBirth, string phoneNumber, string identityCard, string address, int? departmentID, int? divisionID, int? positionID, int? educationID, byte[] profilePicture)
        {
            EmployeeID = employeeID;
            FullName = fullName;
            Gender = gender;
            DateOfBirth = dateOfBirth;
            PhoneNumber = phoneNumber;
            IdentityCard = identityCard;
            Address = address;
            ProfilePicture = profilePicture;
            DepartmentID = departmentID;
            DivisionID = divisionID;
            PositionID = positionID;
            EducationID = educationID;
            
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int EmployeeID { get; set; }

        [StringLength(50)]
        public string FullName { get; set; }

        [StringLength(10)]
        public string Gender { get; set; }

        [Column(TypeName = "date")]
        public DateTime? DateOfBirth { get; set; }

        [StringLength(20)]
        public string PhoneNumber { get; set; }

        [StringLength(20)]
        public string IdentityCard { get; set; }

        [StringLength(100)]
        public string Address { get; set; }

        [StringLength(255)]
        public byte[] ProfilePicture { get; set; }

        public int? DepartmentID { get; set; }

        public int? DivisionID { get; set; }

        public int? PositionID { get; set; }

        public int? EducationID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ACCOUNT> tb_ACCOUNT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ATTENDANCE> tb_ATTENDANCE { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CONTRACT> tb_CONTRACT { get; set; }

        public virtual tb_DEPARTMENT tb_DEPARTMENT { get; set; }

        public virtual tb_DIVISION tb_DIVISION { get; set; }

        public virtual tb_EDUCATION tb_EDUCATION { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_EMPLOYEE_ALLOWANCE> tb_EMPLOYEE_ALLOWANCE { get; set; }

        public virtual tb_POSITION tb_POSITION { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_INSURANCE> tb_INSURANCE { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OVERTIME> tb_OVERTIME { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_REWARD_DISCIPLINE> tb_REWARD_DISCIPLINE { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SALARY_ADVANCE> tb_SALARY_ADVANCE { get; set; }
    }
}

Controllers/tb_EMPLOYEEController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EmployeeManagement.Models;

namespace EmployeeManagement.Controllers
{
    public class tb_EMPLOYEEController : Controller
    {
        private Manage db = new Manage();

        // GET: tb_EMPLOYEE
        public ActionResult Index()
        {
            var tb_EMPLOYEE = db.tb_EMPLOYEE.Include(t => t.tb_DEPARTMENT).Include(t => t.tb_DIVISION).Include(t => t.tb_EDUCATION).Include(t => t.tb_POSITION);
            return View(tb_EMPLOYEE.ToList());
        }

        // GET: tb_EMPLOYEE/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_EMPLOYEE tb_EMPLOYEE = db.tb_EMPLOYEE.Find(id);
            if (tb_EMPLOYEE == null)
            {
                return HttpNotFound();
            }
            return View(tb_EMPLOYEE);
        }

        // GET: tb_EMPLOYEE/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentID = new SelectList(db.tb_DEPARTMENT, "DepartmentID", "DepartmentName");
            ViewBag.DivisionID = new SelectList(db.tb_DIVISION, "DivisionID", "DivisionName");
            ViewBag.EducationID = new SelectList(db.tb_EDUCATION, "EducationID", "EducationName");
            ViewBag.PositionID = new SelectList(db.tb_POSITION, "PositionID", "PositionName");
            return View();
        }

        // POST: tb_EMPLOYEE/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int EmployeeID, string FullName, string Gender, DateTime DateOfBirth, string PhoneNumber, string IdentityCard, string Address, int DepartmentID, int DivisionID, int PositionID, int EducationID, byte[] ProfileImage ) 
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra xem có tệp nào được tải lên không
                tb_EMPLOYEE a = new tb_EMPLOYEE(EmployeeID,FullName,Gender,DateOfBirth,PhoneNumber,IdentityCard,Address,DepartmentID,DivisionID,PositionID,EducationID,ProfileImage);

                // Thêm nhân viên vào cơ sở dữ liệu và lưu
                db.tb_EMPLOYEE.Add(a);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

  
            return RedirectToAction("index");
        }


        public FileContentResult GetImage(int id)
        {
            var employee = db.tb_EMPLOYEE.Find(id);
            if (employee != null && employee.ProfilePicture != null)
            {
                return new FileContentResult(employee.ProfilePicture, "image/jpeg"); // hoặc "image/png" tùy loại ảnh
            }
            string defaultImagePath = Server.MapPath("/image/anhnen.jpg");
            byte[] defaultImage = System.IO.File.ReadAllBytes(defaultImagePath);
            return new FileContentResult(defaultImage, "image/jpeg");
        }


        // GET: tb_EMPLOYEE/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_EMPLOYEE tb_EMPLOYEE = db.tb_EMPLOYEE.Find(id);
            if (tb_EMPLOYEE == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentID = new SelectList(db.tb_DEPARTMENT, "DepartmentID", "DepartmentName", tb_EMPLOYEE.DepartmentID);
            ViewBag.DivisionID = new SelectList(db.tb_DIVISION, "DivisionID", "DivisionName", tb_EMPLOYEE.DivisionID);
            ViewBag.EducationID = new SelectList(db.tb_EDUCATION, "EducationID", "EducationName", tb_EMPLOYEE.EducationID);
            ViewBag.PositionID = new SelectList(db.tb_POSITION, "PositionID", "PositionName", tb_EMPLOYEE.PositionID);
            return View(tb_EMPLOYEE);
        }

        // POST: tb_EMPLOYEE/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeID,FullName,Gender,DateOfBirth,PhoneNumber,IdentityCard,Address,ProfilePicture,DepartmentID,DivisionID,PositionID,EducationID")] tb_EMPLOYEE tb_EMPLOYEE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_EMPLOYEE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentID = new SelectList(db.tb_DEPARTMENT, "DepartmentID", "DepartmentName", tb_EMPLOYEE.DepartmentID);
            ViewBag.DivisionID = new SelectList(db.tb_DIVISION, "DivisionID", "DivisionName", tb_EMPLOYEE.DivisionID);
            ViewBag.EducationID = new SelectList(db.tb_EDUCATION, "EducationID", "EducationName", tb_EMPLOYEE.EducationID);
            ViewBag.PositionID = new SelectList(db.tb_POSITION, "PositionID", "PositionName", tb_EMPLOYEE.PositionID);
            return View(tb_EMPLOYEE);
        }

        // GET: tb_EMPLOYEE/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_EMPLOYEE tb_EMPLOYEE = db.tb_EMPLOYEE.Find(id);
            if (tb_EMPLOYEE == null)
            {
                return HttpNotFound();
            }
            return View(tb_EMPLOYEE);
        }

        // POST: tb_EMPLOYEE/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tb_EMPLOYEE tb_EMPLOYEE = db.tb_EMPLOYEE.Find(id);
            db.tb_EMPLOYEE.Remove(tb_EMPLOYEE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/tb_EMPLOYEE/Create.cshtml
@model EmployeeManagement.Models.tb_EMPLOYEE

@{

}

@using (Html.BeginForm("Create", "tb_EMPLOYEE", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdentityCard, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdentityCard, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdentityCard, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilePicture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ProfilePicture" class="form-control" />
                @Html.ValidationMessageFor(model => model.ProfilePicture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentID, "DepartmentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DivisionID, "DivisionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DivisionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DivisionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PositionID, "PositionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PositionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PositionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EducationID, "EducationID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EducationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EducationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}`

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/tb_EMPLOYEE/Delete.cshtml
@model EmployeeManagement.Models.tb_EMPLOYEE

@{
    ViewBag.Title = "Delete";
}


<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tb_DEPARTMENT.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_DEPARTMENT.DepartmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_DIVISION.DivisionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_DIVISION.DivisionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_EDUCATION.EducationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_EDUCATION.EducationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_POSITION.PositionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_POSITION.PositionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdentityCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdentityCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/tb_EMPLOYEE/Details.cshtml
@model EmployeeManagement.Models.tb_EMPLOYEE

@{
  
}


<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tb_DEPARTMENT.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_DEPARTMENT.DepartmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_DIVISION.DivisionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_DIVISION.DivisionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_EDUCATION.EducationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_EDUCATION.EducationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_POSITION.PositionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_POSITION.PositionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdentityCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdentityCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EmployeeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/tb_EMPLOYEE/Index.cshtml
@model IEnumerable<EmployeeManagement.Models.tb_EMPLOYEE>

@{
    ViewBag.Title = "DANH SÁCH NHÂN VIÊN ";
}


<p>
    <a href="@Url.Action("Create")" class="btn btn-primary mb-3">
        <i class="fa fa-plus"></i> Tạo mới
    </a>
</p>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.tb_DEPARTMENT.DepartmentName)</th>
            <th>@Html.DisplayNameFor(model => model.tb_DIVISION.DivisionName)</th>
            <th>@Html.DisplayNameFor(model => model.tb_EDUCATION.EducationName)</th>
            <th>@Html.DisplayNameFor(model => model.tb_POSITION.PositionName)</th>
            <th>@Html.DisplayNameFor(model => model.FullName)</th>
            <th>@Html.DisplayNameFor(model => model.Gender)</th>
            <th>@Html.DisplayNameFor(model => model.DateOfBirth)</th>
            <th>@Html.DisplayNameFor(model => model.PhoneNumber)</th>
            <th>@Html.DisplayNameFor(model => model.IdentityCard)</th>
            <th>@Html.DisplayNameFor(model => model.Address)</th>
            <th>@Html.DisplayNameFor(model => model.ProfilePicture)</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.tb_DEPARTMENT.DepartmentName)</td>
                <td>@Html.DisplayFor(modelItem => item.tb_DIVISION.DivisionName)</td>
                <td>@Html.DisplayFor(modelItem => item.tb_EDUCATION.EducationName)</td>
                <td>@Html.DisplayFor(modelItem => item.tb_POSITION.PositionName)</td>
                <td>@Html.DisplayFor(modelItem => item.FullName)</td>
                <td>@Html.DisplayFor(modelItem => item.Gender)</td>
                <td>@Html.DisplayFor(modelItem => item.DateOfBirth)</td>
                <td>@Html.DisplayFor(modelItem => item.PhoneNumber)</td>
                <td>@Html.DisplayFor(modelItem => item.IdentityCard)</td>
          
      
                <td>@Html.DisplayFor(modelItem => item.Address)</td>
                <td>


                    <img src="@Url.Action("GetImage", "tb_EMPLOYEE", new { id = item.EmployeeID })" alt="Ảnh đại diện" class="img-thumbnail" style="max-width: 100px;" />

                </td>
                <td>
                    <a href="@Url.Action("Edit", new { id = item.EmployeeID })" class="btn btn-sm btn-warning">
                        <i class="fa fa-edit"></i>
                    </a>
                    <a href="@Url.Action("Details", new { id = item.EmployeeID })" class="btn btn-sm btn-info">
                        <i class="fa fa-info-circle"></i>
                    </a>
                    <a href="@Url.Action("Delete", new { id = item.EmployeeID })" class="btn btn-sm btn-danger">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>